//! Compile-time member-name → method-id intern — split out of
//! `any_method.rs` by the 500-line file discipline (the id
//! constants stay there; this sibling holds the name match).
//! Append-only in lockstep with the constant table.

use crate::any_method::*;
use crate::any_method_date::*;

/// Compile-time name → id intern. `None`-shaped misses map to
/// [`ANY_METHOD_UNKNOWN`] (the runtime throws with the name bytes).
pub fn any_method_id(name: &str) -> i64 {
    match name {
        "push" => ANY_METHOD_PUSH,
        "pop" => ANY_METHOD_POP,
        "charAt" => ANY_METHOD_CHAR_AT,
        "toUpperCase" => ANY_METHOD_TO_UPPER_CASE,
        "toLowerCase" => ANY_METHOD_TO_LOWER_CASE,
        "indexOf" => ANY_METHOD_INDEX_OF,
        "includes" => ANY_METHOD_INCLUDES,
        "slice" => ANY_METHOD_SLICE,
        "split" => ANY_METHOD_SPLIT,
        "trim" => ANY_METHOD_TRIM,
        "trimStart" => ANY_METHOD_TRIM_START,
        "trimEnd" => ANY_METHOD_TRIM_END,
        // Annex B §B.2.3 aliases — the property values ARE the
        // trimStart / trimEnd functions (same mid → same reified
        // cell, so `trimLeft === trimStart` and `.name` answers
        // "trimStart" for free). The typed tier already carries the
        // alias in its name matches.
        "trimLeft" => ANY_METHOD_TRIM_START,
        "trimRight" => ANY_METHOD_TRIM_END,
        "shift" => ANY_METHOD_SHIFT,
        "unshift" => ANY_METHOD_UNSHIFT,
        "join" => ANY_METHOD_JOIN,
        "map" => ANY_METHOD_MAP,
        "filter" => ANY_METHOD_FILTER,
        "forEach" => ANY_METHOD_FOR_EACH,
        "get" => ANY_METHOD_GET,
        "set" => ANY_METHOD_SET,
        "has" => ANY_METHOD_HAS,
        "delete" => ANY_METHOD_DELETE,
        "add" => ANY_METHOD_ADD,
        "clear" => ANY_METHOD_CLEAR,
        "getTime" => ANY_METHOD_GET_TIME,
        "valueOf" => ANY_METHOD_VALUE_OF,
        "toISOString" => ANY_METHOD_TO_ISO_STRING,
        "toJSON" => ANY_METHOD_TO_JSON,
        "getFullYear" => ANY_METHOD_GET_FULL_YEAR,
        "getUTCFullYear" => ANY_METHOD_GET_UTC_FULL_YEAR,
        "getMonth" => ANY_METHOD_GET_MONTH,
        "getUTCMonth" => ANY_METHOD_GET_UTC_MONTH,
        "getDate" => ANY_METHOD_GET_DATE,
        "getUTCDate" => ANY_METHOD_GET_UTC_DATE,
        "getHours" => ANY_METHOD_GET_HOURS,
        "getUTCHours" => ANY_METHOD_GET_UTC_HOURS,
        "getMinutes" => ANY_METHOD_GET_MINUTES,
        "getUTCMinutes" => ANY_METHOD_GET_UTC_MINUTES,
        "getSeconds" => ANY_METHOD_GET_SECONDS,
        "getUTCSeconds" => ANY_METHOD_GET_UTC_SECONDS,
        "getMilliseconds" => ANY_METHOD_GET_MILLISECONDS,
        "getUTCMilliseconds" => ANY_METHOD_GET_UTC_MILLISECONDS,
        "getDay" => ANY_METHOD_GET_DAY,
        "getUTCDay" => ANY_METHOD_GET_UTC_DAY,
        "getTimezoneOffset" => ANY_METHOD_GET_TIMEZONE_OFFSET,
        "setTime" => ANY_METHOD_SET_TIME,
        "setYear" => ANY_METHOD_SET_YEAR,
        "getYear" => ANY_METHOD_GET_YEAR,
        "toGMTString" => ANY_METHOD_TO_GMT_STRING,
        "toUTCString" => ANY_METHOD_TO_UTC_STRING,
        "toDateString" => ANY_METHOD_TO_DATE_STRING,
        "toTimeString" => ANY_METHOD_TO_TIME_STRING,
        "getOrInsert" => ANY_METHOD_GET_OR_INSERT,
        "getOrInsertComputed" => ANY_METHOD_GET_OR_INSERT_COMPUTED,
        "toLocaleString" => ANY_METHOD_TO_LOCALE_STRING,
        "toLocaleDateString" => ANY_METHOD_TO_LOCALE_DATE_STRING,
        "toLocaleTimeString" => ANY_METHOD_TO_LOCALE_TIME_STRING,
        "setFullYear" => ANY_METHOD_SET_FULL_YEAR,
        "setMonth" => ANY_METHOD_SET_MONTH,
        "setDate" => ANY_METHOD_SET_DATE,
        "setHours" => ANY_METHOD_SET_HOURS,
        "setMinutes" => ANY_METHOD_SET_MINUTES,
        "setSeconds" => ANY_METHOD_SET_SECONDS,
        "setMilliseconds" => ANY_METHOD_SET_MILLISECONDS,
        "setUTCFullYear" => ANY_METHOD_SET_UTC_FULL_YEAR,
        "setUTCMonth" => ANY_METHOD_SET_UTC_MONTH,
        "setUTCDate" => ANY_METHOD_SET_UTC_DATE,
        "setUTCHours" => ANY_METHOD_SET_UTC_HOURS,
        "setUTCMinutes" => ANY_METHOD_SET_UTC_MINUTES,
        "setUTCSeconds" => ANY_METHOD_SET_UTC_SECONDS,
        "setUTCMilliseconds" => ANY_METHOD_SET_UTC_MILLISECONDS,
        "toString" => ANY_METHOD_TO_STRING,
        "toFixed" => ANY_METHOD_TO_FIXED,
        "toExponential" => ANY_METHOD_TO_EXPONENTIAL,
        "toPrecision" => ANY_METHOD_TO_PRECISION,
        "match" => ANY_METHOD_MATCH,
        "replace" => ANY_METHOD_REPLACE,
        "replaceAll" => ANY_METHOD_REPLACE_ALL,
        "startsWith" => ANY_METHOD_STARTS_WITH,
        "endsWith" => ANY_METHOD_ENDS_WITH,
        "test" => ANY_METHOD_TEST,
        "exec" => ANY_METHOD_EXEC,
        "compile" => ANY_METHOD_COMPILE,
        "then" => ANY_METHOD_THEN,
        "catch" => ANY_METHOD_CATCH,
        "finally" => ANY_METHOD_FINALLY,
        "call" => ANY_METHOD_CALL,
        "apply" => ANY_METHOD_APPLY,
        "bind" => ANY_METHOD_BIND,
        "hasOwnProperty" => ANY_METHOD_HAS_OWN_PROPERTY,
        "isPrototypeOf" => ANY_METHOD_IS_PROTOTYPE_OF,
        "propertyIsEnumerable" => ANY_METHOD_PROPERTY_IS_ENUMERABLE,
        "__defineGetter__" => ANY_METHOD_DEFINE_GETTER,
        "__defineSetter__" => ANY_METHOD_DEFINE_SETTER,
        "__lookupGetter__" => ANY_METHOD_LOOKUP_GETTER,
        "__lookupSetter__" => ANY_METHOD_LOOKUP_SETTER,
        "lastIndexOf" => ANY_METHOD_LAST_INDEX_OF,
        "reverse" => ANY_METHOD_REVERSE,
        "concat" => ANY_METHOD_CONCAT,
        "fill" => ANY_METHOD_FILL,
        "copyWithin" => ANY_METHOD_COPY_WITHIN,
        "splice" => ANY_METHOD_SPLICE,
        "every" => ANY_METHOD_EVERY,
        "some" => ANY_METHOD_SOME,
        "find" => ANY_METHOD_FIND,
        "findIndex" => ANY_METHOD_FIND_INDEX,
        "reduce" => ANY_METHOD_REDUCE,
        "reduceRight" => ANY_METHOD_REDUCE_RIGHT,
        "sort" => ANY_METHOD_SORT,
        "keys" => ANY_METHOD_KEYS,
        "values" => ANY_METHOD_VALUES,
        "entries" => ANY_METHOD_ENTRIES,
        "next" => ANY_METHOD_NEXT,
        "return" => ANY_METHOD_ITER_RETURN,
        "take" => crate::any_method_iter::ANY_METHOD_TAKE,
        "drop" => crate::any_method_iter::ANY_METHOD_DROP,
        "toArray" => crate::any_method_iter::ANY_METHOD_TO_ARRAY,
        "deref" => crate::any_method_iter::ANY_METHOD_DEREF,
        "anchor" => ANY_METHOD_ANCHOR,
        "fontcolor" => ANY_METHOD_FONTCOLOR,
        "fontsize" => ANY_METHOD_FONTSIZE,
        "link" => ANY_METHOD_LINK,
        "big" => ANY_METHOD_BIG,
        "blink" => ANY_METHOD_BLINK,
        "bold" => ANY_METHOD_BOLD,
        "fixed" => ANY_METHOD_FIXED,
        "italics" => ANY_METHOD_ITALICS,
        "small" => ANY_METHOD_SMALL,
        "strike" => ANY_METHOD_STRIKE,
        "sub" => ANY_METHOD_SUB,
        "sup" => ANY_METHOD_SUP,
        "substring" => ANY_METHOD_SUBSTRING,
        "substr" => ANY_METHOD_SUBSTR,
        "at" => ANY_METHOD_AT,
        "charCodeAt" => ANY_METHOD_CHAR_CODE_AT,
        "padStart" => ANY_METHOD_PAD_START,
        "padEnd" => ANY_METHOD_PAD_END,
        "repeat" => ANY_METHOD_REPEAT,
        "codePointAt" => ANY_METHOD_CODE_POINT_AT,
        "localeCompare" => ANY_METHOD_LOCALE_COMPARE,
        "normalize" => ANY_METHOD_NORMALIZE,
        "toLocaleLowerCase" => ANY_METHOD_TO_LOCALE_LOWER_CASE,
        "toLocaleUpperCase" => ANY_METHOD_TO_LOCALE_UPPER_CASE,
        "search" => ANY_METHOD_SEARCH,
        "matchAll" => ANY_METHOD_MATCH_ALL,
        "isWellFormed" => ANY_METHOD_IS_WELL_FORMED,
        "toWellFormed" => ANY_METHOD_TO_WELL_FORMED,
        "flat" => ANY_METHOD_FLAT,
        "flatMap" => ANY_METHOD_FLAT_MAP,
        "findLast" => ANY_METHOD_FIND_LAST,
        "findLastIndex" => ANY_METHOD_FIND_LAST_INDEX,
        "toReversed" => ANY_METHOD_TO_REVERSED,
        "toSorted" => ANY_METHOD_TO_SORTED,
        "toSpliced" => ANY_METHOD_TO_SPLICED,
        "with" => ANY_METHOD_WITH,
        "union" => ANY_METHOD_UNION,
        "intersection" => ANY_METHOD_INTERSECTION,
        "difference" => ANY_METHOD_DIFFERENCE,
        "symmetricDifference" => ANY_METHOD_SYMMETRIC_DIFFERENCE,
        "isSubsetOf" => ANY_METHOD_IS_SUBSET_OF,
        "isSupersetOf" => ANY_METHOD_IS_SUPERSET_OF,
        "isDisjointFrom" => ANY_METHOD_IS_DISJOINT_FROM,
        // A miss here is not a miss yet — the buffer families' rows
        // live next door, and only their `_` is the real one.
        n => buffer_method_id(n),
    }
}

/// The buffer families' rows — `ArrayBuffer` / `%TypedArray%` /
/// `DataView`, which is a third of this table and grows on its own
/// schedule. Extracted when the parent reached the 200-line function
/// limit; [`crate::any_method_meta::buffer_method_meta`] is the same
/// split on the other side of the same id block.
fn buffer_method_id(name: &str) -> i64 {
    match name {
        "resize" => ANY_METHOD_RESIZE,
        "subarray" => ANY_METHOD_SUBARRAY,
        "transfer" => ANY_METHOD_TRANSFER,
        "transferToFixedLength" => ANY_METHOD_TRANSFER_TO_FIXED_LENGTH,
        "toBase64" => ANY_METHOD_TO_BASE64,
        "toHex" => ANY_METHOD_TO_HEX,
        "setFromBase64" => ANY_METHOD_SET_FROM_BASE64,
        "setFromHex" => ANY_METHOD_SET_FROM_HEX,
        "getInt8" => ANY_METHOD_DV_GET_INT8,
        "setInt8" => ANY_METHOD_DV_SET_INT8,
        "getUint8" => ANY_METHOD_DV_GET_UINT8,
        "setUint8" => ANY_METHOD_DV_SET_UINT8,
        "getInt16" => ANY_METHOD_DV_GET_INT16,
        "setInt16" => ANY_METHOD_DV_SET_INT16,
        "getUint16" => ANY_METHOD_DV_GET_UINT16,
        "setUint16" => ANY_METHOD_DV_SET_UINT16,
        "getInt32" => ANY_METHOD_DV_GET_INT32,
        "setInt32" => ANY_METHOD_DV_SET_INT32,
        "getUint32" => ANY_METHOD_DV_GET_UINT32,
        "setUint32" => ANY_METHOD_DV_SET_UINT32,
        "getFloat16" => ANY_METHOD_DV_GET_FLOAT16,
        "setFloat16" => ANY_METHOD_DV_SET_FLOAT16,
        "getFloat32" => ANY_METHOD_DV_GET_FLOAT32,
        "setFloat32" => ANY_METHOD_DV_SET_FLOAT32,
        "getFloat64" => ANY_METHOD_DV_GET_FLOAT64,
        "setFloat64" => ANY_METHOD_DV_SET_FLOAT64,
        "getBigInt64" => ANY_METHOD_DV_GET_BIGINT64,
        "setBigInt64" => ANY_METHOD_DV_SET_BIGINT64,
        "getBigUint64" => ANY_METHOD_DV_GET_BIGUINT64,
        "setBigUint64" => ANY_METHOD_DV_SET_BIGUINT64,
        _ => ANY_METHOD_UNKNOWN,
    }
}
