//! Ryū algorithm — IEEE 754 double → shortest-roundtrip decimal.
//!
//! Adams 2018 (PLDI):
//! <https://dl.acm.org/doi/10.1145/3192366.3192369>
//!
//! Entry point: [`d2d`] takes raw `f64::to_bits()` and returns
//! [`Decimal64`] = (sign, mantissa, exponent) such that
//! `mantissa · 10^exponent == d` (where d is the original f64
//! interpretation of the bits) for the SHORTEST decimal
//! representation that round-trips through
//! `str::parse::<f64>` back to the same bits.
//!
//! Special values (NaN, ±Infinity, ±0) are NOT handled here —
//! the [`crate::dtoa`] wrapper fast-paths those to literal
//! strings before invoking `d2d`. Subnormals ARE handled — they
//! take the normal Ryū code path with `e2 = 1 - bias - 52 - 2`
//! and `m2 = mantissa` (no implicit leading 1).
//!
//! Tables `POW5_INV_SPLIT[292]` and `POW5_SPLIT[326]` are
//! pre-generated by `scripts/gen_ryu_tables.py`; see
//! [`crate::ryu_tables`] for the const definitions and the
//! generator for the derivation formulas.

use crate::ryu_tables::{
    DOUBLE_POW5_BITCOUNT, DOUBLE_POW5_INV_BITCOUNT, POW5_INV_SPLIT, POW5_SPLIT,
};

const DOUBLE_MANTISSA_BITS: u32 = 52;
const DOUBLE_EXPONENT_BITS: u32 = 11;
const DOUBLE_BIAS: i32 = 1023;

/// Decimal representation of an f64, in the form
/// `sign · mantissa · 10^exponent`.
///
/// - `sign = true` if the input bits had the sign bit set.
/// - `mantissa` is the SHORTEST 1-17 digit decimal that
///   round-trips through `str::parse::<f64>`.
/// - `exponent` is the power-of-10 adjustment.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Decimal64 {
    pub mantissa: u64,
    pub exponent: i32,
    pub sign: bool,
}

/// Convert raw IEEE 754 double bits to a shortest-roundtrip
/// decimal representation.
///
/// Caller MUST ensure `bits` is not a NaN, ±Infinity, or ±0
/// encoding — those are fast-pathed at the wrapper layer.
pub fn d2d(bits: u64) -> Decimal64 {
    // ----------------------------------------------------------
    // Step 1: decode IEEE 754 fields.
    // ----------------------------------------------------------
    let sign = (bits >> (DOUBLE_MANTISSA_BITS + DOUBLE_EXPONENT_BITS)) != 0;
    let ieee_mantissa = bits & ((1u64 << DOUBLE_MANTISSA_BITS) - 1);
    let ieee_exponent =
        ((bits >> DOUBLE_MANTISSA_BITS) as u32) & ((1u32 << DOUBLE_EXPONENT_BITS) - 1);

    // ----------------------------------------------------------
    // Step 2: compute m2 * 2^e2 representation.
    //
    // We shift up by 2 bits to encode the round-up/round-down
    // halfway points as ±1 / ±2 offsets in 4·m2 units (per
    // Adams §3.1).
    // ----------------------------------------------------------
    let (e2, m2): (i32, u64) = if ieee_exponent == 0 {
        // Subnormal: no implicit leading 1.
        (
            1 - DOUBLE_BIAS - DOUBLE_MANTISSA_BITS as i32 - 2,
            ieee_mantissa,
        )
    } else {
        // Normal: implicit leading 1.
        (
            ieee_exponent as i32 - DOUBLE_BIAS - DOUBLE_MANTISSA_BITS as i32 - 2,
            (1u64 << DOUBLE_MANTISSA_BITS) | ieee_mantissa,
        )
    };

    let even = (m2 & 1) == 0;
    let accept_bounds = even;

    // ----------------------------------------------------------
    // Step 3: halfway bounds (scaled by 4).
    //
    //   mv = 4·m2          ← center
    //   mp = 4·m2 + 2      ← upper halfway
    //   mm = 4·m2 - 1 or 2 ← lower halfway (1 at binade boundary, 2 otherwise)
    // ----------------------------------------------------------
    let mv: u64 = 4 * m2;
    let mm_shift: u32 = (ieee_mantissa != 0 || ieee_exponent <= 1) as u32;

    // ----------------------------------------------------------
    // Step 4: scale by 10^(-e10) to bring (mm, mv, mp) · 2^e2
    //         into an integer range we can compare digit-by-digit.
    // ----------------------------------------------------------
    let (mut vr, mut vp, mut vm, e10);
    let mut vm_is_trailing_zeros = false;
    let mut vr_is_trailing_zeros = false;

    if e2 >= 0 {
        let q: u32 = log10_pow2(e2 as u32).saturating_sub((e2 > 3) as u32);
        e10 = q as i32;
        let k: i32 = DOUBLE_POW5_INV_BITCOUNT + pow5_bits(q as i32) - 1;
        let i: i32 = -e2 + q as i32 + k;
        vr = mul_pow5_inv_div_pow2(mv, q, i);
        vp = mul_pow5_inv_div_pow2(mv + 2, q, i);
        vm = mul_pow5_inv_div_pow2(mv - 1 - mm_shift as u64, q, i);

        if q <= 21 {
            // Tracking trailing zeros: vr/vp/vm divide cleanly by
            // 5 only if mv/mv+2/mm do.
            if mv % 5 == 0 {
                vr_is_trailing_zeros = multiple_of_power_of_5(mv, q);
            } else if accept_bounds {
                vm_is_trailing_zeros = multiple_of_power_of_5(mv - 1 - mm_shift as u64, q);
            } else {
                vp -= multiple_of_power_of_5(mv + 2, q) as u64;
            }
        }
    } else {
        let q: u32 = log10_pow5((-e2) as u32).saturating_sub(((-e2) > 1) as u32);
        e10 = q as i32 + e2;
        let i: i32 = -e2 - q as i32;
        let k: i32 = pow5_bits(i) - DOUBLE_POW5_BITCOUNT;
        let j: i32 = q as i32 - k;
        vr = mul_pow5_div_pow2(mv, i as u32, j);
        vp = mul_pow5_div_pow2(mv + 2, i as u32, j);
        vm = mul_pow5_div_pow2(mv - 1 - mm_shift as u64, i as u32, j);

        if q <= 1 {
            // {vr, vp, vm} are q digits short of representing mv
            // exactly; the missing trailing zeros come from the
            // 2^q factor of mv.
            vr_is_trailing_zeros = true;
            if accept_bounds {
                vm_is_trailing_zeros = mm_shift == 1;
            } else {
                vp -= 1;
            }
        } else if q < 63 {
            vr_is_trailing_zeros = multiple_of_power_of_2(mv, q);
        }
    }

    // ----------------------------------------------------------
    // Step 5: find shortest representation by removing trailing
    //         digits while vp and vm still differ in the high
    //         positions.
    // ----------------------------------------------------------
    let mut last_removed_digit: u8 = 0;
    let mut removed: u32 = 0;
    let output;

    if vm_is_trailing_zeros || vr_is_trailing_zeros {
        // Rare path (~0.01%): need to track trailing zeros for
        // correct rounding.
        loop {
            let vp_div10 = vp / 10;
            let vm_div10 = vm / 10;
            if vp_div10 <= vm_div10 {
                break;
            }
            let vm_mod10 = vm % 10;
            vm_is_trailing_zeros &= vm_mod10 == 0;
            vr_is_trailing_zeros &= last_removed_digit == 0;
            last_removed_digit = (vr % 10) as u8;
            vr /= 10;
            vp = vp_div10;
            vm = vm_div10;
            removed += 1;
        }
        if vm_is_trailing_zeros {
            while vm % 10 == 0 {
                vr_is_trailing_zeros &= last_removed_digit == 0;
                last_removed_digit = (vr % 10) as u8;
                vr /= 10;
                vm /= 10;
                removed += 1;
            }
        }
        if vr_is_trailing_zeros && last_removed_digit == 5 && vr % 2 == 0 {
            // Round-half-to-even adjustment.
            last_removed_digit = 4;
        }
        let round_up =
            (vr == vm && (!accept_bounds || !vm_is_trailing_zeros)) || last_removed_digit >= 5;
        output = vr + round_up as u64;
    } else {
        // Common path (~99.99%): no trailing-zero tracking
        // needed. Use a do-while-style loop so the final vp/vm
        // assignments are read for the next iteration's compare,
        // avoiding the `value never read` lint on the tail.
        loop {
            let vp_div10 = vp / 10;
            let vm_div10 = vm / 10;
            if vp_div10 <= vm_div10 {
                break;
            }
            last_removed_digit = (vr % 10) as u8;
            vr /= 10;
            vp = vp_div10;
            vm = vm_div10;
            removed += 1;
        }
        output = vr + ((vr == vm || last_removed_digit >= 5) as u64);
    }

    Decimal64 {
        mantissa: output,
        exponent: e10 + removed as i32,
        sign,
    }
}

/// Number of decimal digits in `v`, 1-17.
pub fn decimal_length(v: u64) -> u8 {
    debug_assert!(v < 10_000_000_000_000_000_000);
    if v >= 10_000_000_000_000_000 {
        17
    } else if v >= 1_000_000_000_000_000 {
        16
    } else if v >= 100_000_000_000_000 {
        15
    } else if v >= 10_000_000_000_000 {
        14
    } else if v >= 1_000_000_000_000 {
        13
    } else if v >= 100_000_000_000 {
        12
    } else if v >= 10_000_000_000 {
        11
    } else if v >= 1_000_000_000 {
        10
    } else if v >= 100_000_000 {
        9
    } else if v >= 10_000_000 {
        8
    } else if v >= 1_000_000 {
        7
    } else if v >= 100_000 {
        6
    } else if v >= 10_000 {
        5
    } else if v >= 1_000 {
        4
    } else if v >= 100 {
        3
    } else if v >= 10 {
        2
    } else {
        1
    }
}

// ==========================================================
// Intrinsics
// ==========================================================

/// Bit length of 5^e (i.e., `floor(log2(5^e)) + 1`).
/// Valid for e ∈ [0, 3528]; we only use e ∈ [0, 325].
fn pow5_bits(e: i32) -> i32 {
    debug_assert!(e >= 0);
    debug_assert!(e <= 3528);
    // log2(5) ≈ 2.321928. Approximation: e * 1217359 / 2^19.
    ((e * 1217359) >> 19) + 1
}

/// `floor(e * log10(2))` for e ∈ [0, 1650].
fn log10_pow2(e: u32) -> u32 {
    debug_assert!(e <= 1650);
    // log10(2) ≈ 0.30103. Approximation: e * 78913 / 2^18.
    (e * 78913) >> 18
}

/// `floor(e * log10(5))` for e ∈ [0, 2620].
fn log10_pow5(e: u32) -> u32 {
    debug_assert!(e <= 2620);
    // log10(5) ≈ 0.69897. Approximation: e * 732923 / 2^20.
    (e * 732923) >> 20
}

/// Compute `(m * mul) >> j` where `mul` is a 128-bit value
/// stored as `(lo, hi)`.
///
/// We compute the high 128 bits of `m * mul` (`b2` plus the
/// carry from `b0`), then shift right by `j - 64` to get a u64.
fn mul_shift_64(m: u64, mul: (u64, u64), j: i32) -> u64 {
    debug_assert!(j > 64);
    debug_assert!(j < 160);
    let b0 = (m as u128) * (mul.0 as u128);
    let b2 = (m as u128) * (mul.1 as u128);
    let sum = (b0 >> 64) + b2;
    (sum >> (j - 64)) as u64
}

fn mul_pow5_inv_div_pow2(m: u64, q: u32, j: i32) -> u64 {
    debug_assert!((q as usize) < POW5_INV_SPLIT.len());
    // SAFETY: `q` is `log10_pow2(e2) - (e2 > 3)` for a double's
    // binary exponent, bounded by the table's construction (upstream
    // ryu indexes it unchecked for the same reason); the checked
    // form's panic path was a `core::fmt` edge in every program that
    // prints a float (r505).
    let mul = unsafe { *POW5_INV_SPLIT.get_unchecked(q as usize) };
    mul_shift_64(m, mul, j)
}

fn mul_pow5_div_pow2(m: u64, i: u32, j: i32) -> u64 {
    debug_assert!((i as usize) < POW5_SPLIT.len());
    // SAFETY: as above — `i` is `-e2 - q`, within the table by
    // construction.
    let mul = unsafe { *POW5_SPLIT.get_unchecked(i as usize) };
    mul_shift_64(m, mul, j)
}

/// Count the number of times `value` is divisible by 5.
fn pow5_factor(mut value: u64) -> u32 {
    let mut count = 0;
    while value > 0 {
        if value % 5 != 0 {
            return count;
        }
        value /= 5;
        count += 1;
    }
    0
}

fn multiple_of_power_of_5(value: u64, p: u32) -> bool {
    pow5_factor(value) >= p
}

fn multiple_of_power_of_2(value: u64, p: u32) -> bool {
    debug_assert!(p < 64);
    (value & ((1u64 << p) - 1)) == 0
}

#[cfg(test)]
mod tests {
    use super::*;

    extern crate alloc;
    use alloc::format;
    use alloc::string::String;

    /// Reformat a `Decimal64` into the same string `f64::to_string`
    /// would emit (modulo the JS spec post-process), for direct
    /// comparison.
    ///
    /// This is a test helper — production formatting lives in
    /// `dtoa::format_f64_into` (P12.1-S3).
    fn dec_to_string(d: Decimal64) -> String {
        if d.mantissa == 0 {
            return if d.sign {
                String::from("-0")
            } else {
                String::from("0")
            };
        }
        let digits = format!("{}", d.mantissa);
        let n_digits = digits.len() as i32;
        let abs_exponent = d.exponent + n_digits - 1;
        let mut out = String::new();
        if d.sign {
            out.push('-');
        }
        // Match Rust's `f64::to_string` convention: use plain
        // decimal for "reasonable" magnitudes; use exponent form
        // otherwise. Reasonable here = same range as JS spec
        // shortest-roundtrip (-6 ≤ E < n_digits + d.exponent), but
        // for the unit-test convenience we mimic Rust's `{}`
        // (slightly different threshold).
        if abs_exponent >= -4 && abs_exponent < 16 {
            // Plain decimal form.
            if d.exponent >= 0 {
                out.push_str(&digits);
                for _ in 0..d.exponent {
                    out.push('0');
                }
            } else {
                let dot_pos = n_digits + d.exponent;
                if dot_pos <= 0 {
                    out.push_str("0.");
                    for _ in 0..(-dot_pos) {
                        out.push('0');
                    }
                    out.push_str(&digits);
                } else {
                    out.push_str(&digits[..dot_pos as usize]);
                    out.push('.');
                    out.push_str(&digits[dot_pos as usize..]);
                }
            }
        } else {
            // Exponential form: d.dddE±NN.
            out.push(digits.as_bytes()[0] as char);
            if n_digits > 1 {
                out.push('.');
                out.push_str(&digits[1..]);
            }
            out.push('e');
            let exp = abs_exponent;
            if exp >= 0 {
                out.push('+');
            }
            out.push_str(&format!("{}", exp));
        }
        out
    }

    /// Round-trip sanity: every sample's d2d output should parse
    /// back to the same f64 bits.
    fn assert_round_trip(d: f64) {
        let dec = d2d(d.to_bits());
        // Reconstruct as a string and parse with str::parse.
        let s = dec_to_string(dec);
        let parsed: f64 = s
            .parse()
            .unwrap_or_else(|_| panic!("could not parse Ryū output {s:?} back to f64 (input {d})"));
        assert_eq!(
            parsed.to_bits(),
            d.to_bits(),
            "round-trip failed: input {d} → {s:?} → parsed {parsed}"
        );
    }

    #[test]
    fn d2d_one() {
        let dec = d2d(1.0_f64.to_bits());
        assert_eq!(
            dec,
            Decimal64 {
                mantissa: 1,
                exponent: 0,
                sign: false
            }
        );
    }

    #[test]
    fn d2d_negative_one() {
        let dec = d2d((-1.0_f64).to_bits());
        assert_eq!(
            dec,
            Decimal64 {
                mantissa: 1,
                exponent: 0,
                sign: true
            }
        );
    }

    #[test]
    fn d2d_ten() {
        let dec = d2d(10.0_f64.to_bits());
        // 10 = 1 · 10^1
        assert_eq!(
            dec,
            Decimal64 {
                mantissa: 1,
                exponent: 1,
                sign: false
            }
        );
    }

    #[test]
    fn d2d_one_tenth() {
        let dec = d2d(0.1_f64.to_bits());
        // 0.1 = 1 · 10^-1
        assert_eq!(
            dec,
            Decimal64 {
                mantissa: 1,
                exponent: -1,
                sign: false
            }
        );
    }

    #[test]
    fn d2d_pi_short() {
        let dec = d2d(3.14_f64.to_bits());
        // shortest round-trip = 314 · 10^-2
        assert_eq!(
            dec,
            Decimal64 {
                mantissa: 314,
                exponent: -2,
                sign: false
            }
        );
    }

    #[test]
    fn d2d_zero_point_one_plus_zero_point_two() {
        // 0.1 + 0.2 = 0x3FD3333333333334 = shortest "0.30000000000000004"
        let v = 0.1_f64 + 0.2_f64;
        let dec = d2d(v.to_bits());
        assert_eq!(
            dec,
            Decimal64 {
                mantissa: 30000000000000004,
                exponent: -17,
                sign: false
            }
        );
    }

    /// 1e21 = 0x4458180000000000 → mantissa=1 exp=21.
    #[test]
    fn d2d_1e21() {
        let dec = d2d(1e21_f64.to_bits());
        assert_eq!(
            dec,
            Decimal64 {
                mantissa: 1,
                exponent: 21,
                sign: false
            }
        );
    }

    #[test]
    fn d2d_1e_minus_7() {
        let dec = d2d(1e-7_f64.to_bits());
        assert_eq!(
            dec,
            Decimal64 {
                mantissa: 1,
                exponent: -7,
                sign: false
            }
        );
    }

    #[test]
    fn d2d_min_positive_subnormal() {
        // smallest subnormal positive = 5e-324
        let dec = d2d(f64::MIN_POSITIVE.to_bits());
        // f64::MIN_POSITIVE = 2^-1022, which is NOT subnormal — it's the
        // smallest normal. Round-trip is what matters.
        assert_round_trip(f64::MIN_POSITIVE);
        // mantissa exists; just sanity-check shape
        assert!(dec.mantissa > 0);
        assert!(dec.exponent < 0);
        assert!(!dec.sign);
    }

    #[test]
    fn d2d_smallest_subnormal() {
        // 5e-324 = denorm
        let bits: u64 = 0x0000_0000_0000_0001;
        let dec = d2d(bits);
        assert_round_trip(f64::from_bits(bits));
        assert!(dec.mantissa > 0);
        assert!(!dec.sign);
    }

    #[test]
    fn d2d_max_value() {
        // f64::MAX = 1.7976931348623157e308
        assert_round_trip(f64::MAX);
        let dec = d2d(f64::MAX.to_bits());
        assert_eq!(
            dec,
            Decimal64 {
                mantissa: 17976931348623157,
                exponent: 292,
                sign: false
            }
        );
    }

    #[test]
    fn d2d_epsilon() {
        assert_round_trip(f64::EPSILON);
    }

    #[test]
    fn round_trip_sweep() {
        let samples: &[f64] = &[
            1.0,
            -1.0,
            2.0,
            -2.0,
            0.1,
            0.2,
            0.3,
            0.5,
            -0.5,
            3.14159265358979323846,
            2.718281828459045,
            f64::MIN_POSITIVE,
            f64::EPSILON,
            f64::MAX,
            f64::MIN,
            42.0,
            -42.0,
            100.0,
            1000.0,
            10000.0,
            100000.0,
            1_000_000.0,
            1e15,
            1e16,
            1e20,
            1e21,
            1e22,
            1e-5,
            1e-10,
            1e-300,
            1e308,
            -1e308,
            123.456,
            -987.654,
            0.0001,
            0.00001,
            7.0,
            1.7976931348623157e308,
            5e-324,
        ];
        for &d in samples {
            assert_round_trip(d);
        }
    }

    #[test]
    fn intrinsics_log10_pow2() {
        assert_eq!(log10_pow2(0), 0);
        assert_eq!(log10_pow2(1), 0); // log10(2) ≈ 0.301
        assert_eq!(log10_pow2(10), 3); // log10(1024) ≈ 3.01
        assert_eq!(log10_pow2(20), 6); // log10(2^20) ≈ 6.02
    }

    #[test]
    fn intrinsics_log10_pow5() {
        assert_eq!(log10_pow5(0), 0);
        assert_eq!(log10_pow5(1), 0); // log10(5) ≈ 0.699
        assert_eq!(log10_pow5(10), 6); // log10(5^10) ≈ 6.99
        assert_eq!(log10_pow5(100), 69); // log10(5^100) ≈ 69.9
    }

    #[test]
    fn intrinsics_pow5_bits() {
        assert_eq!(pow5_bits(0), 1); // 5^0 = 1, 1 bit
        assert_eq!(pow5_bits(1), 3); // 5 = 101, 3 bits
        assert_eq!(pow5_bits(10), 24); // 5^10 = 9765625, bit_length 24
    }

    #[test]
    fn intrinsics_pow5_factor() {
        assert_eq!(pow5_factor(1), 0);
        assert_eq!(pow5_factor(5), 1);
        assert_eq!(pow5_factor(25), 2);
        assert_eq!(pow5_factor(100), 2); // 100 = 4 · 25
        assert_eq!(pow5_factor(125), 3);
    }
}
