#!/usr/bin/env python3
"""Generate torajs-str's case-mapping tables from UCD UnicodeData.txt +
SpecialCasing.txt.

Usage:
    python3 gen_case_tables.py <ucd-dir> > crates/torajs-str/src/case_table.rs

`<ucd-dir>` is a directory containing UnicodeData.txt + SpecialCasing.txt
(download from https://www.unicode.org/Public/<ver>/ucd/). The UCD
version itself is captured in a header comment so we know which release
the tables track.

This is a host-side codegen step: the output `case_table.rs` is checked
in. To upgrade UCD, re-run the script with the new data and commit the
diff. We do NOT pull UCD at build time (0 build-time deps; the
generated tables are plain Rust source code).

Output tables:

- `SIMPLE_UPPER: &[(u32, u32)]` — sorted by source cp. Maps cp -> upper cp.
- `SIMPLE_LOWER: &[(u32, u32)]` — sorted by source cp. Maps cp -> lower cp.
- `FULL_UPPER: &[(u32, &[u32])]` — sorted by source cp. Maps cp -> multi
  cp expansion (Unconditional only from SpecialCasing.txt).
- `FULL_LOWER: &[(u32, &[u32])]` — sorted, same shape.

Caller is responsible for:
- Decoding the input string to code points (Latin-1 / UTF-16 LE
  encoding-aware walk).
- For each cp, looking up Full first (returns multi-cp), falling back
  to Simple (returns single cp), falling back to identity (cp unchanged).
- Computing the output encoding (Latin-1 vs UTF-16) by scanning all
  mapped cps for max value.
- Re-encoding into a fresh StrBlock.

Final_Sigma context-dependent mapping (`Σ -> ς` when preceded by Cased,
not followed by Cased) is NOT exported by this script — it requires a
Cased property table + per-position context check. That lands as
P11.5-A3 (separate substrate sub-step).
"""

import sys
import os

def parse_unicode_data(path):
    """Parse UnicodeData.txt. Return (simple_upper, simple_lower) dicts."""
    simple_upper = {}  # source_cp -> upper_cp
    simple_lower = {}  # source_cp -> lower_cp
    with open(path) as f:
        for line in f:
            line = line.rstrip()
            if not line or line.startswith('#'):
                continue
            fields = line.split(';')
            if len(fields) < 15:
                continue
            cp = int(fields[0], 16)
            # field 12 = Simple_Uppercase_Mapping, 13 = Simple_Lowercase_Mapping
            upper_str = fields[12].strip()
            lower_str = fields[13].strip()
            if upper_str:
                simple_upper[cp] = int(upper_str, 16)
            if lower_str:
                simple_lower[cp] = int(lower_str, 16)
    return simple_upper, simple_lower


def parse_special_casing(path):
    """Parse SpecialCasing.txt. Return (full_upper, full_lower) dicts of
    cp -> list[cp] for Unconditional entries only."""
    full_upper = {}
    full_lower = {}
    with open(path) as f:
        for line in f:
            raw = line.rstrip()
            if not raw or raw.startswith('#'):
                continue
            # Strip comment from end (everything after '#').
            comment_idx = raw.find('#')
            if comment_idx >= 0:
                payload = raw[:comment_idx]
            else:
                payload = raw
            fields = [f.strip() for f in payload.split(';')]
            # Format: cp; lower; title; upper; (condition_list;)?
            # After stripping comment, trailing semicolon leaves an empty
            # last field. Filter trailing empties to find the condition.
            while fields and fields[-1] == '':
                fields.pop()
            if len(fields) < 4:
                continue
            cp = int(fields[0], 16)
            lower_seq = parse_cp_seq(fields[1])
            upper_seq = parse_cp_seq(fields[3])
            # condition_list at index 4 if present
            condition = fields[4] if len(fields) >= 5 else ''
            if condition:
                # Skip Locale / Final_Sigma / etc — Unconditional only.
                continue
            # Only emit if the Full mapping differs from identity (it
            # always does for SpecialCasing entries, but be defensive).
            if lower_seq != [cp]:
                full_lower[cp] = lower_seq
            if upper_seq != [cp]:
                full_upper[cp] = upper_seq
    return full_upper, full_lower


def parse_cp_seq(s):
    """Parse a space-separated hex cp sequence into list[int]."""
    return [int(tok, 16) for tok in s.split() if tok]


def emit_rust(simple_upper, simple_lower, full_upper, full_lower, ucd_version):
    """Emit the case_table.rs source as a single string."""
    out = []
    out.append('// CODEGEN: scripts/ucd/gen_case_tables.py — file-size audit carve-out (file-size.md #1).')
    out.append('//! UCD case-mapping tables — auto-generated by')
    out.append('//! `scripts/ucd/gen_case_tables.py` from UnicodeData.txt +')
    out.append('//! SpecialCasing.txt. DO NOT EDIT BY HAND.')
    out.append('//!')
    out.append(f'//! UCD version: {ucd_version}')
    out.append('//!')
    out.append('//! Tables:')
    out.append('//! - `SIMPLE_UPPER` / `SIMPLE_LOWER`: source-cp -> 1-cp mapping')
    out.append('//! - `FULL_UPPER` / `FULL_LOWER`: source-cp -> N-cp expansion')
    out.append('//!   (SpecialCasing.txt Unconditional entries only)')
    out.append('//!')
    out.append('//! Final_Sigma (context-dependent `Σ -> ς`) is NOT in these')
    out.append('//! tables — see P11.5-A3 follow-up substrate work.')
    out.append('//!')
    out.append('//! All tables are sorted by source cp for binary search.')
    out.append('')
    out.append('#![allow(clippy::unreadable_literal)]')
    out.append('')
    out.append('#[allow(dead_code)]')
    out.append(f'pub(crate) const UCD_VERSION: &str = "{ucd_version}";')
    out.append('')

    # Simple tables — straightforward
    out.append(emit_simple_table('SIMPLE_UPPER', simple_upper))
    out.append('')
    out.append(emit_simple_table('SIMPLE_LOWER', simple_lower))
    out.append('')

    # Full tables — slice-of-slice. Each entry is (cp, &'static [u32]).
    out.append(emit_full_table('FULL_UPPER', full_upper))
    out.append('')
    out.append(emit_full_table('FULL_LOWER', full_lower))
    out.append('')

    out.append('/// Look up `cp` in a sorted `(u32, u32)` simple-mapping table.')
    out.append('/// Returns `Some(mapped)` if found, else `None`. Binary search')
    out.append('/// — O(log N) per lookup, N ~1500 per direction.')
    out.append('#[inline]')
    out.append('pub(crate) fn simple_lookup(table: &[(u32, u32)], cp: u32) -> Option<u32> {')
    out.append('    table')
    out.append('        .binary_search_by_key(&cp, |&(k, _)| k)')
    out.append('        .ok()')
    out.append('        .map(|i| table[i].1)')
    out.append('}')
    out.append('')
    out.append('/// Look up `cp` in a sorted `(u32, &[u32])` full-mapping table.')
    out.append('/// Returns `Some(slice)` if found, else `None`.')
    out.append('#[inline]')
    out.append(
        "pub(crate) fn full_lookup(table: &[(u32, &'static [u32])], cp: u32) -> Option<&'static [u32]> {"
    )
    out.append('    table')
    out.append('        .binary_search_by_key(&cp, |&(k, _)| k)')
    out.append('        .ok()')
    out.append('        .map(|i| table[i].1)')
    out.append('}')

    return '\n'.join(out) + '\n'


def emit_simple_table(name, mapping):
    lines = []
    sorted_items = sorted(mapping.items())
    lines.append(f'/// {len(sorted_items)} entries.')
    lines.append(f'pub(crate) static {name}: &[(u32, u32)] = &[')
    for src, dst in sorted_items:
        lines.append(f'    (0x{src:04X}, 0x{dst:04X}),')
    lines.append('];')
    return '\n'.join(lines)


def emit_full_table(name, mapping):
    lines = []
    sorted_items = sorted(mapping.items())
    lines.append(f'/// {len(sorted_items)} entries (Unconditional SpecialCasing only).')
    lines.append(f"pub(crate) static {name}: &[(u32, &'static [u32])] = &[")
    for src, seq in sorted_items:
        seq_lit = ', '.join(f'0x{c:04X}' for c in seq)
        lines.append(f'    (0x{src:04X}, &[{seq_lit}]),')
    lines.append('];')
    return '\n'.join(lines)


def main():
    if len(sys.argv) != 2:
        print(f'usage: {sys.argv[0]} <ucd-dir>', file=sys.stderr)
        sys.exit(2)
    ucd_dir = sys.argv[1]
    udp = os.path.join(ucd_dir, 'UnicodeData.txt')
    scp = os.path.join(ucd_dir, 'SpecialCasing.txt')
    if not os.path.isfile(udp) or not os.path.isfile(scp):
        print(f'error: missing UnicodeData.txt or SpecialCasing.txt under {ucd_dir}', file=sys.stderr)
        sys.exit(1)

    # Detect UCD version from SpecialCasing.txt header (e.g. "# SpecialCasing-16.0.0.txt").
    ucd_version = 'unknown'
    with open(scp) as f:
        for line in f:
            if line.startswith('# SpecialCasing-'):
                ucd_version = line.split('SpecialCasing-')[1].split('.txt')[0]
                break

    simple_upper, simple_lower = parse_unicode_data(udp)
    full_upper, full_lower = parse_special_casing(scp)

    print(emit_rust(simple_upper, simple_lower, full_upper, full_lower, ucd_version), end='')


if __name__ == '__main__':
    main()
