#!/usr/bin/env python3
"""Generate torajs-ucd's identifier tables from UCD DerivedCoreProperties.txt.

Usage:
    python3 gen_id_tables.py <ucd-dir> > crates/torajs-ucd/src/id_table.rs

`<ucd-dir>` is a directory containing DerivedCoreProperties.txt (download
from https://www.unicode.org/Public/<ver>/ucd/). Same host-side codegen
pattern as gen_norm_tables.py / gen_case_tables.py: the output
`id_table.rs` is checked in, so there is no build-time UCD dependency.
A UCD upgrade means re-running this script and committing the diff.

Emits two range tables covering the cp >= 0x80 portion only, matching the
crate-wide convention that ASCII is bitmap-tested by the caller (see the
`UCD_LETTER` / `UCD_NUMBER` doc comments):

- `ID_START: &[Range]`    — Unicode `ID_Start`, the derived property
  ECMAScript §12.7.1 `UnicodeIDStart` refers to verbatim.
- `ID_CONTINUE: &[Range]` — Unicode `ID_Continue` plus U+200C ZWNJ and
  U+200D ZWJ. ECMAScript names those two separately in
  `IdentifierPartChar` (they are *not* in the Unicode property), so they
  are folded in here rather than special-cased at every call site.

Note `$` and `_` are also IdentifierStartChar per §12.7.1, but both are
ASCII and therefore the caller's business.
"""

import sys
import os

UCD_VERSION = "17.0.0"

# ES2024 §12.7.1 IdentifierPartChar :: <ZWNJ> | <ZWJ>. Not part of the
# Unicode ID_Continue property, so the generator adds them explicitly.
ES_EXTRA_CONTINUE = [(0x200C, 0x200D)]


def parse_derived_core_properties(path, wanted):
    """Collect inclusive (lo, hi) ranges carrying property `wanted`."""
    ranges = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            fields = [f.strip() for f in line.split(";")]
            if len(fields) < 2 or fields[1] != wanted:
                continue
            cps = fields[0]
            if ".." in cps:
                lo, hi = cps.split("..")
                ranges.append((int(lo, 16), int(hi, 16)))
            else:
                cp = int(cps, 16)
                ranges.append((cp, cp))
    return ranges


def merge(ranges, floor):
    """Drop everything below `floor`, then sort + coalesce touching ranges."""
    clipped = []
    for lo, hi in ranges:
        if hi < floor:
            continue
        clipped.append((max(lo, floor), hi))
    clipped.sort()

    merged = []
    for lo, hi in clipped:
        if merged and lo <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(merged[-1][1], hi))
        else:
            merged.append((lo, hi))
    return merged


def emit_table(name, doc, ranges):
    # Blank line goes *before* the table so the file ends without one —
    # rustfmt strips a trailing blank, and a generator whose output is not
    # already fmt-clean reopens the drift on every regeneration.
    print()
    print(f"/// {doc}")
    print(f"pub static {name}: &[Range] = &[")
    for lo, hi in ranges:
        print(f"    (0x{lo:04X}, 0x{hi:04X}),")
    print("];")


def main():
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 1
    ucd = sys.argv[1]
    dcp_path = os.path.join(ucd, "DerivedCoreProperties.txt")
    if not os.path.exists(dcp_path):
        print(f"error: {dcp_path} not found", file=sys.stderr)
        return 1

    id_start = merge(parse_derived_core_properties(dcp_path, "ID_Start"), 0x80)
    id_continue = merge(
        parse_derived_core_properties(dcp_path, "ID_Continue") + ES_EXTRA_CONTINUE,
        0x80,
    )

    print("// CODEGEN: scripts/ucd/gen_id_tables.py — file-size audit carve-out (file-size.md #1).")
    print("//! UCD identifier tables — auto-generated by")
    print("//! `scripts/ucd/gen_id_tables.py` from DerivedCoreProperties.txt.")
    print("//! DO NOT EDIT BY HAND.")
    print("//!")
    print(f"//! UCD version: {UCD_VERSION}")
    print("//!")
    print("//! Both tables cover the cp >= 0x80 portion only — ASCII is the")
    print("//! caller's business, per the `UCD_LETTER` / `UCD_NUMBER` convention.")
    print("//! `ID_CONTINUE` folds in U+200C ZWNJ and U+200D ZWJ, which")
    print("//! ECMAScript §12.7.1 names separately in `IdentifierPartChar`.")
    print()
    print("use crate::Range;")
    emit_table(
        "ID_START",
        "Unicode `ID_Start`, cp >= 0x80 portion. ES §12.7.1 `UnicodeIDStart`.",
        id_start,
    )
    emit_table(
        "ID_CONTINUE",
        "Unicode `ID_Continue` + ZWNJ/ZWJ, cp >= 0x80 portion. "
        "ES §12.7.1 `UnicodeIDContinue` plus the two explicitly-named joiners.",
        id_continue,
    )
    print(f"// ID_START ranges: {len(id_start)}", file=sys.stderr)
    print(f"// ID_CONTINUE ranges: {len(id_continue)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
