//! AST — arena-allocated. Children referenced by `ExprId(u32)`, not Box.

pub(crate) mod accessor_lookup;
mod apply_args;
mod apply_args_materialize;
mod apply_args_recv;
mod apply_rest_args;
mod apply_spread;
mod apply_spread_hoist;
mod apply_spread_math;
mod apply_spread_push;
mod arguments_object;
mod arguments_object_bodies;
mod arguments_object_chain;
mod arguments_object_collect;
mod arguments_object_ctor_argv;
mod arguments_object_devirt;
mod arguments_object_headless_argv;
mod arguments_object_inject;
mod arguments_object_method_argv;
mod arguments_object_mutation;
mod arguments_object_objlit_argv;
mod arguments_object_rewrite;
mod arguments_object_rewrite_recurse;
mod arguments_object_rewrite_spread;
mod arguments_object_rewrite_stmt;
mod arguments_object_sloppy;
mod arguments_object_stages;
mod arguments_object_static_argv;
mod arguments_object_synth;
mod arguments_object_walkers;
mod arguments_object_walkers_return;
mod arrow_arguments_alias;
pub(crate) use arguments_object_walkers::{
    body_has_arguments_length, body_has_non_length_arguments_touch,
};
pub(crate) mod arguments_object_escape_store;
mod build_factory;
pub(crate) mod capturing_classes;
mod class_globals;
mod class_globals_register;
mod class_globals_shadow;
mod clone_body;
mod clone_body_tables;
mod closure_capture_anns;
mod closure_capture_anns_outer;
mod control_flow;
mod delete_bare_name;
mod desugar_async;
mod desugar_classes;
mod desugar_classes_abstract;
pub(crate) mod desugar_classes_builtin_heritage;
mod desugar_classes_ctor_return;
mod desugar_classes_default_ctor;
mod desugar_classes_dispatch;
mod desugar_classes_emit;
mod desugar_classes_field_inits;
mod desugar_classes_fields;
mod desugar_classes_generic_twin;
mod desugar_classes_method_owners;
mod desugar_classes_pass2;
mod desugar_classes_pass3;
mod desugar_classes_statics;
mod desugar_classes_super;
mod desugar_classes_super_prop;
mod desugar_eval;
mod desugar_generators;
mod desugar_generators_alpha;
mod desugar_generators_assemble;
mod desugar_generators_class;
mod desugar_generators_field_ann;
mod desugar_generators_forof;
mod desugar_generators_lift;
mod desugar_generators_methods;
mod desugar_generators_prep;
mod desugar_generators_rewrite;
mod desugar_generators_sm;
mod desugar_generators_sm_finally;
mod desugar_generators_sm_loops;
mod desugar_generators_sm_return;
mod desugar_generators_sm_rewrite;
mod desugar_generators_sm_try;
mod desugar_generators_walkers;
mod desugar_objlit_super;
mod desugar_using;
mod desugar_variadic_push;
mod dflt_param_tdz;
mod escape_analyze;
mod export_names;
mod expr;
mod fill_optional_fields;
mod fn_constructor;
mod fn_constructor_argc;
mod fn_constructor_assign;
mod fnexpr_bind_this;
pub(crate) mod fnexpr_this;
mod fnexpr_this_alias;
pub(crate) mod fnexpr_this_args;
mod fnexpr_this_args_valueops;
pub(crate) mod fnexpr_this_call_faces;
pub(crate) mod fnexpr_this_cb_slots;
mod fnexpr_this_default;
mod fnexpr_this_default_alias;
mod fnexpr_this_default_slots;
mod fnexpr_this_default_userfn;
mod fnexpr_this_default_writes;
pub(crate) mod fnexpr_this_faces;
mod fnexpr_this_member_ret;
mod fnexpr_this_names;
mod fnexpr_this_pairing;
pub(crate) mod fnexpr_this_recvs;
pub(crate) mod fnexpr_this_routed;
mod fnexpr_this_shapes;
mod fnexpr_this_unclaimed;
mod fold_fromentries;
mod forwarders;
mod forwarders_object;
mod forwarders_object_mismatch;
mod forwarders_object_synth;
mod free_vars;
mod free_vars_decls;
mod free_vars_globals;
mod gen_fn_expr;
mod globalthis_member;
mod heritage;
mod hoist_gen_fn_exprs;
mod hoist_nested_classes;
mod hoist_nested_classes_admit;
mod hoist_nested_classes_census;
mod hoist_nested_classes_rename;
mod implicit_generics_cb_ret;
mod implicit_generics_infer;
mod implicit_generics_value_return;
mod infer_closure_lets;
mod infer_closure_params;
mod infer_closure_params_apply;
mod infer_closure_params_helpers;
mod infer_closure_params_hof;
mod infer_closure_params_promise;
mod infer_closure_this_scope;
mod infer_closure_typevars;
mod inject_builtin_classes;
mod inject_builtin_classes_cause;
mod inject_builtin_classes_data;
mod inject_builtin_classes_message;
mod inject_disposable_stack;
mod lift_arrow_fns;
mod module_passes;
mod named_eval;
mod namedfn_recv_cb;
pub(crate) mod nested_closure_captures;
mod nested_fns;
mod nested_fns_capture;
mod nested_fns_idents;
mod ns_alias;
pub(crate) mod objlit_nominal;
mod objlit_nominal_anylane;
mod objlit_nominal_returned;
mod prop_key;
mod prototype_call;
mod readonly_globals;
mod sfi_pass;
mod sfi_rewrite;
mod sfi_safe;
mod sig_thunk;
mod sloppy_implicit_globals;
pub(crate) mod sloppy_this_prologue;
mod spread_callee_wrap;
mod stmt;
mod stmt_class;
mod stmt_flat;
pub(crate) mod stmt_nested_lists;
mod strict_reserved_goal;
mod super_collect;
mod super_collect_prop;
mod this_param;
mod toplevel_this;
mod uncallable_builtins;
mod uninit_let;
mod var_hoist;
mod yield_ident_goal;
pub use apply_args::apply_default_args;
pub use apply_args_materialize::materialize_expr_defaults;
pub use apply_rest_args::apply_rest_args;
pub use apply_spread::apply_spread_args;
pub use arguments_object::desugar_arguments_object;
pub use arrow_arguments_alias::alias_arrow_arguments;
pub(crate) use build_factory::build_factory_body;
pub use class_globals::synthesize_class_globals;
pub(crate) use clone_body::clone_toplevel_stmt;
pub(crate) use closure_capture_anns::{SiteAnns, collect_closure_capture_anns};
pub(crate) use closure_capture_anns_outer::collect_outer_binds;
pub(crate) use control_flow::body_always_terminates;
pub use delete_bare_name::triage_delete_bare_names;
pub(crate) use desugar_async::UNDEF_SLOT_MARKER;
pub use desugar_async::desugar_async;
pub use desugar_classes::desugar_classes;
pub use desugar_classes_pass2::route_non_class_new;
pub use desugar_eval::desugar_eval;
pub use desugar_generators::desugar_generators;
pub(crate) use desugar_generators_alpha::rebinds_in_stmt;
pub(crate) use desugar_generators_walkers::expand_yield_into_in_stmt;
pub use desugar_objlit_super::desugar_objlit_super;
pub use desugar_using::desugar_using;
pub use desugar_variadic_push::desugar_variadic_push;
pub use escape_analyze::escape_analyze_array_literals;
pub use export_names::triage_duplicate_exports;
pub use expr::{BinOp, Expr, ExprId, Param, UnaryOp};
pub use fill_optional_fields::fill_optional_fields;
pub use fn_constructor::synthesize_fn_constructors;
pub use fnexpr_bind_this::{
    normalize_function_bind_call, promote_bind_receiver_this, register_bind_receiver_recv_fns,
};
pub use fnexpr_this_default::bind_fnexpr_this_default;
pub use fnexpr_this_unclaimed::unclaimed_fnexpr_this;
pub use fold_fromentries::fold_fromentries;
pub use forwarders::synthesize_forwarders;
pub(crate) use forwarders::{push_gen_argv_spread, split_gen_argv_tail};
pub use forwarders_object::{synthesize_fn_to_closure_forwarders, tag_struct_field_closure_types};
pub(crate) use free_vars::free_idents_of_stmt;
pub(crate) use free_vars::is_global_name as free_vars_is_global_name;
pub use gen_fn_expr::{GenFnExprInfo, GenFnExprKind};
pub use globalthis_member::desugar_globalthis_members;
pub use hoist_gen_fn_exprs::hoist_gen_fn_exprs;
pub(crate) use implicit_generics_infer::{
    AstExprsView, binds_to_params, infer_expr_ann_with, infer_return_ann, infer_return_ann_seeded,
};
pub(crate) use implicit_generics_value_return::body_has_value_return;
pub use infer_closure_params::infer_anonymous_closure_params;
pub(crate) use inject_builtin_classes::class_reaches_error;
pub use inject_builtin_classes::inject_builtin_classes;
pub use inject_disposable_stack::inject_disposable_stack;
pub use lift_arrow_fns::lift_arrow_fns;
pub(crate) use lift_arrow_fns::{
    default_init_for_field, default_init_for_type, is_fn_arr_ann, is_fn_like_ann,
    method_owner_is_in_chain, retag_field_fn_ann, rewrite_this_in_ann,
};
pub use module_passes::{desugar_builtin_imports, rename_user_main, unwrap_exports};
pub(crate) use named_eval::collect_named_eval_positions;
pub use namedfn_recv_cb::synthesize_recv_cb_forwarders;
pub use nested_fns::desugar_nested_fns;
pub use nested_fns_capture::desugar_capturing_nested_fns;
pub(crate) use nested_fns_idents::rename_fn_self_refs;
pub use ns_alias::desugar_ns_alias_members;
pub use prop_key::{literal_prop_key, number_prop_key};
pub use prototype_call::desugar_prototype_call;
pub use readonly_globals::resolve_readonly_global_writes;
pub use readonly_globals::resolve_readonly_ns_prop_writes;
pub use sfi_pass::rewrite_split_for_i_to_iter;
pub use sig_thunk::synthesize_sig_thunks;
pub use sloppy_implicit_globals::synthesize_sloppy_implicit_globals;
pub use spread_callee_wrap::wrap_dynamic_spread_callees;
pub use stmt::{ExportStar, Stmt, SwitchCase};
pub(crate) use stmt::{GEN_ARGV_PARAM, GEN_METHOD_PREFIX, GEN_RECV_PARAM};
pub use stmt_class::{AccessorKind, ClassCtor, ClassMethod, StaticField, StaticInit, Visibility};
pub use uncallable_builtins::resolve_uncallable_builtin_calls;
pub(crate) mod desugar_with;
pub(crate) use desugar_with::{WITH_OBJ_FN, WITH_OBJ_PREFIX};
mod number_template_sites;
mod with_object_widen;
pub use desugar_with::{WithReject, desugar_with};
pub use number_template_sites::number_template_sites;
pub use stmt_flat::toplevel_stmts_flat;
pub use strict_reserved_goal::triage_strict_reserved_idents;
pub use this_param::bind_this_param;
pub use toplevel_this::rewrite_toplevel_this;
pub use uninit_let::desugar_uninit_let;
pub use var_hoist::desugar_var_hoist;
pub use with_object_widen::widen_with_object_bindings;
pub use yield_ident_goal::triage_yield_idents;

mod ast_def;
pub use ast_def::*;
