//! Name-classifier pair pulled out of [`crate::check`] as chunk-327
//! of the check.rs god-file decomp.
//!
//! Two `&str` → `bool` predicates used by call-dispatch / member-access
//! sites:
//!
//! - `is_class_method_name` — M5.1: detects synthetic class-method and
//!   virtual-dispatch entry-points minted by `desugar_classes`
//!   (`__cm_*` / `__dispatch_*` prefixes). Drives the first-arg-borrow
//!   carve-out and the same predicate also gates ssa_lower's
//!   transfer/drop emission for arg[0] of these calls.
//! - `is_array_method_name` — T-29: built-in `Array.prototype` method
//!   name allowlist recognized by the per-method `Call` dispatch.
//!   The `Member`-on-`Array` catch-all uses this to avoid shadowing
//!   built-in methods with `Type::Any` when a bare `arr.method` access
//!   appears outside a call site.
//!
//! Re-exported into `crate::check` so callers
//! (`check_type_of_member_array`, `check_type_of_call_dispatch_flags`,
//! `check_type_of_member_prim_union`, …) keep their `crate::check::<name>`
//! import paths.

/// M5.1 — class methods (and constructors) generated by `desugar_classes`
/// carry the `__cm_` prefix. The first argument of any such call is the
/// receiver (`__this`) and must be passed by borrow — neither check.rs's
/// affine consume nor ssa_lower's transfer/drop logic should fire on
/// arg[0] of these calls. Args[1..] follow the normal rules.
/// `__dispatch_` is the H.3.b synthetic virtual-dispatch entry; same
/// shape (arg[0] is borrow receiver, struct-prefix-subtype widening on
/// the call), so it shares the predicate.
pub fn is_class_method_name(name: &str) -> bool {
    name.starts_with("__cm_") || name.starts_with("__dispatch_")
}

/// T-29 — built-in Array.prototype method names recognized by the
/// per-method Call-dispatch in check.rs. The Member-on-Array
/// catch-all uses this to avoid shadowing them with Type::Any when
/// a bare `arr.method` access appears outside a call site.
pub(crate) fn is_array_method_name(name: &str) -> bool {
    matches!(
        name,
        "push"
            | "pop"
            | "shift"
            | "unshift"
            | "slice"
            | "splice"
            | "concat"
            | "join"
            | "reverse"
            | "sort"
            | "indexOf"
            | "lastIndexOf"
            | "includes"
            | "find"
            | "findIndex"
            | "findLast"
            | "findLastIndex"
            | "map"
            | "filter"
            | "reduce"
            | "reduceRight"
            | "forEach"
            | "every"
            | "some"
            | "flat"
            | "flatMap"
            | "fill"
            | "copyWithin"
            | "at"
            | "entries"
            | "keys"
            | "values"
            | "toString"
            | "toLocaleString"
            | "toReversed"
            | "toSorted"
            | "toSpliced"
            | "with"
            | "indexOfStartingAt"
    )
}
