//! Pass 0 `declare_intrinsic` group: Date class runtime (v0.2 #2,
//! Phase 2.0a + 2.0b + 2.0b.2 + T-30 setters/annexB).
//!
//! chunk 117 continuation of the Pass 0 multi-sub-sibling split
//! (chunks 110-116). 42 declarations covering ctor / drop /
//! valueOf-isoString / local + UTC getters/setters / component ctor +
//! parse.
//!
//! - Ctor / lifecycle / valueOf: `now`, `from_ms`, `drop`,
//!   `now_static` (Date.now), `get_time` (.getTime/.valueOf),
//!   `to_iso_string` (.toISOString).
//! - Setters (T-30): `set_time`, `get_year`/`set_year` (annexB),
//!   `set_full_year`/`set_month`/`set_date`,
//!   `set_hours`/`set_minutes`/`set_seconds`/`set_milliseconds`.
//! - String rendering: `to_gmt_string`, `to_date_string`,
//!   `to_locale_string`, `to_locale_date_string`,
//!   `to_locale_time_string`.
//! - Local getters: `get_full_year`/`get_month`/`get_date` +
//!   `get_hours`/`get_minutes`/`get_seconds`/`get_milliseconds` +
//!   `get_day` + `get_timezone_offset`.
//! - UTC getters: `get_utc_*` mirror of the local getters.
//! - Component ctor / parse (Phase 2.0b.2):
//!   `from_components(y,mo,d,h,mi,s,ms) -> Date`,
//!   `utc_components(...) -> i64` (Date.UTC),
//!   `from_iso(s) -> Date` (`new Date(string)`),
//!   `parse_iso(s) -> F64` (Date.parse).

use std::collections::HashMap;

use crate::ssa::{FuncId, Module, Type};
use crate::ssa_lower::declare_intrinsic;

pub(crate) struct DateIds {
    pub date_now: FuncId,
    pub date_from_ms: FuncId,
    pub date_drop: FuncId,
    pub date_now_static: FuncId,
    pub date_get_time: FuncId,
    pub date_to_iso_string: FuncId,
    pub date_set_time: FuncId,
    pub date_get_year: FuncId,
    pub date_set_year: FuncId,
    pub date_to_gmt_string: FuncId,
    pub date_to_date_string: FuncId,
    pub date_to_locale_string: FuncId,
    pub date_to_locale_date_string: FuncId,
    pub date_to_locale_time_string: FuncId,
    pub date_set_full_year: FuncId,
    pub date_set_month: FuncId,
    pub date_set_date: FuncId,
    pub date_set_hours: FuncId,
    pub date_set_minutes: FuncId,
    pub date_set_seconds: FuncId,
    pub date_set_milliseconds: FuncId,
    pub date_get_full_year: FuncId,
    pub date_get_month: FuncId,
    pub date_get_date: FuncId,
    pub date_get_hours: FuncId,
    pub date_get_minutes: FuncId,
    pub date_get_seconds: FuncId,
    pub date_get_milliseconds: FuncId,
    pub date_get_day: FuncId,
    pub date_get_timezone_offset: FuncId,
    pub date_get_utc_full_year: FuncId,
    pub date_get_utc_month: FuncId,
    pub date_get_utc_date: FuncId,
    pub date_get_utc_hours: FuncId,
    pub date_get_utc_minutes: FuncId,
    pub date_get_utc_seconds: FuncId,
    pub date_get_utc_milliseconds: FuncId,
    pub date_get_utc_day: FuncId,
    pub date_from_components: FuncId,
    pub date_utc_components: FuncId,
    pub date_from_iso: FuncId,
    pub date_parse_iso: FuncId,
}

pub(crate) fn declare(module: &mut Module, fn_table: &mut HashMap<String, FuncId>) -> DateIds {
    let seven_i64 = &[
        Type::I64,
        Type::I64,
        Type::I64,
        Type::I64,
        Type::I64,
        Type::I64,
        Type::I64,
    ];
    DateIds {
        date_now: declare_intrinsic(module, fn_table, "__torajs_date_now", &[], Type::Date),
        date_from_ms: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_from_ms",
            &[Type::I64],
            Type::Date,
        ),
        date_drop: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_drop",
            &[Type::Date],
            Type::Void,
        ),
        date_now_static: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_now_static",
            &[],
            Type::I64,
        ),
        date_get_time: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_time",
            &[Type::Date],
            Type::I64,
        ),
        date_to_iso_string: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_to_iso_string",
            &[Type::Date],
            Type::Str,
        ),
        date_set_time: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_set_time",
            &[Type::Date, Type::I64],
            Type::I64,
        ),
        date_get_year: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_year",
            &[Type::Date],
            Type::I64,
        ),
        date_set_year: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_set_year",
            &[Type::Date, Type::I64],
            Type::I64,
        ),
        date_to_gmt_string: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_to_gmt_string",
            &[Type::Date],
            Type::Str,
        ),
        date_to_date_string: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_to_date_string",
            &[Type::Date],
            Type::Str,
        ),
        date_to_locale_string: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_to_locale_string",
            &[Type::Date],
            Type::Str,
        ),
        date_to_locale_date_string: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_to_locale_date_string",
            &[Type::Date],
            Type::Str,
        ),
        date_to_locale_time_string: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_to_locale_time_string",
            &[Type::Date],
            Type::Str,
        ),
        date_set_full_year: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_set_full_year",
            &[Type::Date, Type::I64, Type::I64, Type::I64],
            Type::I64,
        ),
        date_set_month: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_set_month",
            &[Type::Date, Type::I64, Type::I64],
            Type::I64,
        ),
        date_set_date: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_set_date",
            &[Type::Date, Type::I64],
            Type::I64,
        ),
        date_set_hours: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_set_hours",
            &[Type::Date, Type::I64, Type::I64, Type::I64, Type::I64],
            Type::I64,
        ),
        date_set_minutes: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_set_minutes",
            &[Type::Date, Type::I64, Type::I64, Type::I64],
            Type::I64,
        ),
        date_set_seconds: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_set_seconds",
            &[Type::Date, Type::I64, Type::I64],
            Type::I64,
        ),
        date_set_milliseconds: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_set_milliseconds",
            &[Type::Date, Type::I64],
            Type::I64,
        ),
        date_get_full_year: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_full_year",
            &[Type::Date],
            Type::I64,
        ),
        date_get_month: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_month",
            &[Type::Date],
            Type::I64,
        ),
        date_get_date: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_date",
            &[Type::Date],
            Type::I64,
        ),
        date_get_hours: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_hours",
            &[Type::Date],
            Type::I64,
        ),
        date_get_minutes: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_minutes",
            &[Type::Date],
            Type::I64,
        ),
        date_get_seconds: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_seconds",
            &[Type::Date],
            Type::I64,
        ),
        date_get_milliseconds: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_milliseconds",
            &[Type::Date],
            Type::I64,
        ),
        date_get_day: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_day",
            &[Type::Date],
            Type::I64,
        ),
        date_get_timezone_offset: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_timezone_offset",
            &[Type::Date],
            Type::I64,
        ),
        date_get_utc_full_year: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_utc_full_year",
            &[Type::Date],
            Type::I64,
        ),
        date_get_utc_month: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_utc_month",
            &[Type::Date],
            Type::I64,
        ),
        date_get_utc_date: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_utc_date",
            &[Type::Date],
            Type::I64,
        ),
        date_get_utc_hours: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_utc_hours",
            &[Type::Date],
            Type::I64,
        ),
        date_get_utc_minutes: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_utc_minutes",
            &[Type::Date],
            Type::I64,
        ),
        date_get_utc_seconds: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_utc_seconds",
            &[Type::Date],
            Type::I64,
        ),
        date_get_utc_milliseconds: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_utc_milliseconds",
            &[Type::Date],
            Type::I64,
        ),
        date_get_utc_day: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_get_utc_day",
            &[Type::Date],
            Type::I64,
        ),
        date_from_components: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_from_components",
            seven_i64,
            Type::Date,
        ),
        date_utc_components: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_utc_components",
            seven_i64,
            Type::I64,
        ),
        date_from_iso: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_from_iso",
            &[Type::Str],
            Type::Date,
        ),
        date_parse_iso: declare_intrinsic(
            module,
            fn_table,
            "__torajs_date_parse_iso",
            &[Type::Str],
            Type::F64,
        ),
    }
}
