#!/usr/bin/env python3
"""Generate torajs-date's IANA-zone → CLDR long-name table.

Usage:
    python3 gen_tz_names.py <cldr-dir> > crates/torajs-date/src/tz_names.rs

`<cldr-dir>` is a directory containing:
- metaZones.json       (cldr-json: cldr-core/supplemental/metaZones.json)
- timeZoneNames.json   (cldr-json: cldr-dates-full/main/en/timeZoneNames.json)
- bcp47-timezone.json  (cldr-json: cldr-bcp47/bcp47/timezone.json)

Same host-side codegen pattern as scripts/ucd/gen_*_tables.py: the
output tz_names.rs is checked in; a CLDR upgrade = re-run with fresh
data and commit the diff. We do NOT pull CLDR at build time (0
build-time deps; the generated table is plain Rust source).

Mapping (what `Date.prototype.toString`'s "(Japan Standard Time)"
suffix needs, mirroring what ICU hands V8/JSC):

- metaZones.json  metazoneInfo.timezone.* nested tree → IANA zone id
  ("Asia/Tokyo") → its usesMetazone history; we take the LAST entry
  (the currently-active metazone — historical segments have `_to`).
- timeZoneNames.json  metazone.<mzone>.long.standard / .daylight →
  the display names. Zones with a zone-level long override (e.g.
  Etc/UTC → "Coordinated Universal Time") use that instead.
- Zones with neither metazone nor override are omitted — the runtime
  falls back to the numeric "GMT+HHMM" form for those.
- bcp47 `_alias` groups fan every CLDR canonical id out to its IANA
  aliases ("Asia/Calcutta" is CLDR-canonical; the modern IANA id is
  "Asia/Kolkata"; TZ=UTC resolves through the Etc/UTC group), so a
  TZ value or /etc/localtime target hits the table under any spelling.

Output: `TZ_LONG_NAMES: &[(&str, &str, &str)]` — (zone_id, standard,
daylight), sorted by zone_id for binary search. A metazone with no
daylight name repeats the standard name (such zones never observe
DST, so the slot is unreachable anyway).
"""

import json
import sys
from pathlib import Path


def walk_zones(node, path, out):
    """Flatten the metazoneInfo nested tree into (zone_id, mzone)."""
    if isinstance(node, list):
        # usesMetazone history — last entry is the active one
        last = node[-1].get("usesMetazone", {})
        mzone = last.get("_mzone")
        if mzone:
            out["/".join(path)] = mzone
        return
    for key, child in node.items():
        walk_zones(child, path + [key], out)


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen_tz_names.py <cldr-dir>")
    cldr = Path(sys.argv[1])

    meta = json.loads((cldr / "metaZones.json").read_text())
    names = json.loads((cldr / "timeZoneNames.json").read_text())

    version = meta["supplemental"]["version"]["_cldrVersion"]
    tree = meta["supplemental"]["metaZones"]["metazoneInfo"]["timezone"]
    zone_to_mzone = {}
    walk_zones(tree, [], zone_to_mzone)

    tzn = names["main"]["en"]["dates"]["timeZoneNames"]
    mz_names = tzn["metazone"]

    rows = {}
    for zone, mzone in zone_to_mzone.items():
        long = mz_names.get(mzone, {}).get("long", {})
        std = long.get("standard")
        if not std:
            continue
        dst = long.get("daylight", std)
        rows[zone] = (std, dst)

    # zone-level long-name overrides (Etc/UTC and friends). These are
    # PARTIAL: Europe/London carries only long.daylight ("British
    # Summer Time") and inherits standard from its metazone — so merge
    # field-by-field over whatever the metazone pass produced.
    def walk_overrides(node, path):
        if "long" in node and isinstance(node["long"], dict):
            zone = "/".join(path)
            base_std, base_dst = rows.get(zone, (None, None))
            std = node["long"].get("standard", base_std)
            dst = node["long"].get("daylight", base_dst if base_dst else std)
            if std:
                rows[zone] = (std, dst)
        for key, child in node.items():
            if key != "long" and isinstance(child, dict):
                walk_overrides(child, path + [key])

    walk_overrides(tzn["zone"], [])

    # fan each canonical id out to its IANA alias group (bcp47 _alias
    # lists space-separated equivalent ids, first = CLDR canonical)
    bcp47 = json.loads((cldr / "bcp47-timezone.json").read_text())
    for entry in bcp47["keyword"]["u"]["tz"].values():
        if not isinstance(entry, dict):
            continue
        ids = entry.get("_alias", "").split()
        named = next((i for i in ids if i in rows), None)
        if named:
            for alias in ids:
                rows.setdefault(alias, rows[named])

    print(
        "// CODEGEN: scripts/gen_tz_names.py — file-size audit carve-out (file-size.md #1)."
    )
    print("//! IANA-zone → CLDR en long-name table — auto-generated by")
    print("//! `scripts/gen_tz_names.py` from CLDR metaZones.json +")
    print("//! timeZoneNames.json. DO NOT EDIT BY HAND.")
    print("//!")
    print(f"//! CLDR version: {version}")
    print()
    print("/// `(zone_id, standard, daylight)` sorted by `zone_id` for")
    print("/// binary search (`crate::tz::zone_long_name`).")
    print("pub static TZ_LONG_NAMES: &[(&str, &str, &str)] = &[")
    for zone in sorted(rows):
        std, dst = rows[zone]
        print(f'    ("{zone}", "{std}", "{dst}"),')
    print("];")


if __name__ == "__main__":
    main()
