const s: any = "hi";
const f = s.toUpperCase;
console.log(f.name);
console.log(f.length);
console.log(typeof f.name);
console.log(s.toUpperCase.name);
console.log(s.slice.length);
const a: any = [1, 2];
console.log(a.push.name);
console.log(a.push.length);
const m: any = new Map();
console.log(m.set.name);
console.log(m.set.length);
const d: any = new Date(0);
console.log(d.getTime.name);
console.log(d.getTime.length);
console.log(f.call.name);
console.log(f.call.length);
console.log(f.apply.length);
console.log(f);
const arr2: any = [f];
console.log(arr2);
const n: any = 5;
console.log(n.toFixed.name);
console.log(n.toFixed.length);
