var a = [];
console.log(a.pop());
console.log(a.shift());
console.log(a.length);
var b = [1];
console.log(b.pop());
console.log(b.length);
var c = [1, 2];
console.log(c.shift());
console.log(c.shift());
console.log(c.length);
var t = [1];
t.pop();
t.pop();
t.pop();
console.log(t.length);
const d: number[] = [];
d.pop();
d.shift();
console.log(d.length);
var e = ["x"];
console.log(e.pop());
e.pop();
console.log(e.length);
