var a = new Array();
a[100] = 7;
console.log(a[100]);
console.log(a.length);
console.log(a[50]);
var b = [];
b[3] = "x";
b[0] = 1;
console.log(b.length);
console.log(b[0]);
console.log(b[1]);
console.log(b[3]);
var s = [];
s[2] = null;
s[0] = 1.5;
console.log(s.length);
console.log(s[2]);
console.log(s[0]);
var big = [];
big[5555] = 5.5;
console.log(big.length);
console.log(big[5555]);
console.log(big[3000]);
var inb = [];
inb[0] = 1;
inb[1] = 2;
inb[0] = 9;
console.log(inb[0]);
console.log(inb.length);
